name: container-signing-and-verifying
on:
  push:
    branches: [ main ]

jobs:
  sign-images:
    runs-on: ubuntu-latest
    environment: POC-Image-Signing-Docker-Hub
    permissions:
      contents: read
      id-token: write # needed for signing the images with GitHub OIDC Token

    name: sign-images
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sign and verify the images with GitHub OIDC Token
        run: |
          images=""
          while IFS= read -r line || [ -n "$line" ]; do
            images="${images} ${line}"
          done < images.txt
          images="${images# }"
          cosign sign --yes ${images}
          cosign verify ${images} \
          --certificate-identity=https://github.com/${{ github.repository }}/.github/workflows/sign-images.yml@${{ github.ref }} \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com